In [30]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "player": ["Virat", "Rohit", "Virat", "Dhoni", "Rohit"],
    "team": ["India", "India", "India", "India", "India"],
    "city": ["Delhi", "Mumbai", "Delhi", "Chennai", "Delhi"],
    "runs": [80, 45, 100, np.nan, 60],
    "balls": [60, 30, 70, 10, 40],
    "result": ["Win", "Win", "Loss", "Win", "Loss"]
})

print(df)

  player   team     city   runs  balls result
0  Virat  India    Delhi   80.0     60    Win
1  Rohit  India   Mumbai   45.0     30    Win
2  Virat  India    Delhi  100.0     70   Loss
3  Dhoni  India  Chennai    NaN     10    Win
4  Rohit  India    Delhi   60.0     40   Loss

In [8]:
df.value_counts('player')
df.value_counts('city')

df.value_counts('result')
print(df['result'].value_counts())

result
Win     3
Loss    2
Name: count, dtype: int64

In [11]:
df['player'].unique()

array(['Virat', 'Rohit', 'Dhoni'], dtype=object)

In [13]:
#we can also count the number of unique values

print(df['player'].nunique())

3

In [19]:
# by default unique does not count NaN values

print(df['runs'].nunique())
print(df['runs'].nunique(dropna=False))

df['runs'].nunique()==df['runs'].nunique(dropna= False)

4
5

False

In [15]:
## for sorting the dataframes

df.sort_values(by='runs',ascending= False)

  player   team     city   runs  balls result
2  Virat  India    Delhi  100.0     70   Loss
0  Virat  India    Delhi   80.0     60    Win
4  Rohit  India    Delhi   60.0     40   Loss
1  Rohit  India   Mumbai   45.0     30    Win
3  Dhoni  India  Chennai    NaN     10    Win

In [22]:
# we can get the ranks with the help of sort_values and rank functions

df['runs_rank']= df['runs'].rank(ascending= False)

print(df)

  player   team     city   runs  balls result  runs_rank
0  Virat  India    Delhi   80.0     60    Win        2.0
1  Rohit  India   Mumbai   45.0     30    Win        4.0
2  Virat  India    Delhi  100.0     70   Loss        1.0
3  Dhoni  India  Chennai    NaN     10    Win        NaN
4  Rohit  India    Delhi   60.0     40   Loss        3.0

In [31]:
##sort_index

#below will sort the dataframe based on column index
# the columns are going to be sort based on alphabetical order
df.sort_index(axis= 1)
##

print(df)
##below is row wise sort_index
df.sort_index(axis=0)
print(df)

  player   team     city   runs  balls result
0  Virat  India    Delhi   80.0     60    Win
1  Rohit  India   Mumbai   45.0     30    Win
2  Virat  India    Delhi  100.0     70   Loss
3  Dhoni  India  Chennai    NaN     10    Win
4  Rohit  India    Delhi   60.0     40   Loss
  player   team     city   runs  balls result
0  Virat  India    Delhi   80.0     60    Win
1  Rohit  India   Mumbai   45.0     30    Win
2  Virat  India    Delhi  100.0     70   Loss
3  Dhoni  India  Chennai    NaN     10    Win
4  Rohit  India    Delhi   60.0     40   Loss

In [34]:
#wew can also mark any columns as our index column

df.set_index('player', inplace= True)

In [36]:
# we can also set multiple columns as our index
df.set_index(["runs", "city"])

                team  balls result
runs  city
80.0  Delhi    India     60    Win
45.0  Mumbai   India     30    Win
100.0 Delhi    India     70   Loss
NaN   Chennai  India     10    Win
60.0  Delhi    India     40   Loss

In [37]:
# we can also reset the index that we had given

df.reset_index()

  player   team     city   runs  balls result
0  Virat  India    Delhi   80.0     60    Win
1  Rohit  India   Mumbai   45.0     30    Win
2  Virat  India    Delhi  100.0     70   Loss
3  Dhoni  India  Chennai    NaN     10    Win
4  Rohit  India    Delhi   60.0     40   Loss

In [40]:
# we can also check for null values

df.isnull()

#if we want the sum of all the null values
df.isnull().sum()

#above will give us the number of null values per column

team      0
city      0
runs      1
balls     0
result    0
dtype: int64

In [44]:
#notnull

df['runs'].notnull()

player
Virat     True
Rohit     True
Virat     True
Dhoni    False
Rohit     True
Name: runs, dtype: bool

In [47]:
## fill the na values
df['runs']= df['runs'].fillna(df['runs'].mean())

print(df)

         team     city    runs  balls result
player
Virat   India    Delhi   80.00     60    Win
Rohit   India   Mumbai   45.00     30    Win
Virat   India    Delhi  100.00     70   Loss
Dhoni   India  Chennai   71.25     10    Win
Rohit   India    Delhi   60.00     40   Loss