In [2]:
## getting started with Pandas in Python
import numpy as np
import pandas as pd

In [3]:
##Panda Series
##1-D arrya holding data of any type

country=['India', 'USA', 'Pakistan']

df= pd.Series(country)
print(df)

0       India
1         USA
2    Pakistan
dtype: object

In [4]:
marks=[90,29,34,45,66]
subjects=['maths', 'pyhsics','checm', 'bio','hindi']

my_score= pd.Series(marks, index=subjects, name='My_marks')

print(my_score)
print(my_score['maths'])

maths      90
pyhsics    29
checm      34
bio        45
hindi      66
Name: My_marks, dtype: int64
90

In [5]:
dic= {
    'maths':90,
    'chem':45
}

marks= pd.Series(dic)
print(marks)

maths    90
chem     45
dtype: int64

In [6]:
marks.is_unique## return true if all the elements are unique

True

In [7]:
my_score.values

array([90, 29, 34, 45, 66])

In [8]:
my_score.size

5

In [9]:
ind= my_score.index
print(ind)
print(ind[0])

Index(['maths', 'pyhsics', 'checm', 'bio', 'hindi'], dtype='object')
maths

In [28]:
df= pd.read_csv('customer_data.csv')

df1=df.squeeze('columns')
print(df1)
dff= pd.read_csv('customer_data.csv', index_col='Age')

       CustomerID  Age  Gender  Tenure  Usage Frequency  Support Calls  \
0               1   22  Female      25               14              4
1               2   41  Female      28               28              7
2               3   47    Male      27               10              2
3               4   35    Male       9               12              5
4               5   53  Female      58               24              9
...           ...  ...     ...     ...              ...            ...
64369       64370   45  Female      33               12              6
64370       64371   37    Male       6                1              5
64371       64372   25    Male      39               14              8
64372       64373   50  Female      18               19              7
64373       64374   52  Female      45               15              9

       Payment Delay Subscription Type Contract Length  Total Spend  \
0                 27             Basic         Monthly          598
1                 13          Standard         Monthly          584
2                 29           Premium          Annual          757
3                 17           Premium       Quarterly          232
4                  2          Standard          Annual          533
...              ...               ...             ...          ...
64369             21             Basic       Quarterly          947
64370             22          Standard          Annual          923
64371             30           Premium         Monthly          327
64372             22          Standard         Monthly          540
64373             25          Standard         Monthly          696

       Last Interaction  Churn
0                     9      1
1                    20      0
2                    21      0
3                    18      0
4                    18      0
...                 ...    ...
64369                14      1
64370                 9      1
64371                20      1
64372                13      1
64373                22      1

[64374 rows x 12 columns]

In [11]:
df.sample()

## give one data row randomly

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
49567,49568,30,Male,48,30,10,18,Basic,Annual,835,11,1

In [50]:
##value_counts

## frequency count of data

df.value_counts #it gives frequency of each data point for each columns in data
print(df.value_counts)
print(df.value_counts('Gender'))
##gives frequency of each gender

<bound method DataFrame.value_counts of        CustomerID  Age  Gender  Tenure  Usage Frequency  Support Calls  \
0               1   22  Female      25               14              4
1               2   41  Female      28               28              7
2               3   47    Male      27               10              2
3               4   35    Male       9               12              5
4               5   53  Female      58               24              9
...           ...  ...     ...     ...              ...            ...
64369       64370   45  Female      33               12              6
64370       64371   37    Male       6                1              5
64371       64372   25    Male      39               14              8
64372       64373   50  Female      18               19              7
64373       64374   52  Female      45               15              9

       Payment Delay Subscription Type Contract Length  Total Spend  \
0                 27             Basic         Monthly          598
1                 13          Standard         Monthly          584
2                 29           Premium          Annual          757
3                 17           Premium       Quarterly          232
4                  2          Standard          Annual          533
...              ...               ...             ...          ...
64369             21             Basic       Quarterly          947
64370             22          Standard          Annual          923
64371             30           Premium         Monthly          327
64372             22          Standard         Monthly          540
64373             25          Standard         Monthly          696

       Last Interaction  Churn
0                     9      1
1                    20      0
2                    21      0
3                    18      0
4                    18      0
...                 ...    ...
64369                14      1
64370                 9      1
64371                20      1
64372                13      1
64373                22      1

[64374 rows x 12 columns]>
Gender
Female    34353
Male      30021
Name: count, dtype: int64

In [24]:
## below will change the original array
df.sort_values('Age', inplace=True)
## below will not make permanent changes in the array
df.sort_values('Age')

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
44228,44229,18,Female,1,25,4,22,Premium,Monthly,451,26,1
27813,27814,18,Female,59,24,6,7,Basic,Annual,847,15,0
44289,44290,18,Female,3,28,9,24,Basic,Annual,418,30,1
56919,56920,18,Female,12,27,7,21,Basic,Quarterly,154,11,1
40330,40331,18,Female,12,15,8,26,Standard,Monthly,449,29,1
...,...,...,...,...,...,...,...,...,...,...,...,...
55560,55561,65,Male,60,4,4,8,Standard,Monthly,878,29,1
24971,24972,65,Male,1,30,4,6,Premium,Monthly,529,15,0
50295,50296,65,Female,1,22,0,27,Standard,Monthly,954,7,1
63499,63500,65,Male,26,1,4,29,Basic,Quarterly,744,19,1
61512,61513,65,Female,60,13,6,27,Premium,Monthly,559,27,1

In [18]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
17057,17058,18,Male,45,21,4,6,Basic,Annual,943,13,0
49896,49897,18,Male,44,29,5,25,Basic,Annual,818,8,1
17009,17010,18,Male,34,11,8,11,Standard,Annual,311,21,0
1472,1473,18,Female,28,21,4,18,Basic,Monthly,371,20,0
23210,23211,18,Male,24,28,0,22,Standard,Monthly,135,26,0

In [22]:
df.sort_values('Tenure', ascending=False).head(1).values[0]

array([22817, 26, 'Female', 60, 23, 7, 10, 'Standard', 'Monthly', 452, 27,
       0], dtype=object)

In [ ]:
dff.sort_index()
##this is going to sort the index column which was given in the data frame dff= pd.read_csv('customer_data.csv', index_col='Age')

,CustomerID,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
Age,,,,,,,,,,,
18,17058,Male,45,21,4,6,Basic,Annual,943,13,0
18,49897,Male,44,29,5,25,Basic,Annual,818,8,1
18,17010,Male,34,11,8,11,Standard,Annual,311,21,0
18,1473,Female,28,21,4,18,Basic,Monthly,371,20,0
18,23211,Male,24,28,0,22,Standard,Monthly,135,26,0
...,...,...,...,...,...,...,...,...,...,...,...
65,136,Female,26,17,10,25,Basic,Annual,254,1,1
65,64235,Female,42,14,3,28,Premium,Monthly,939,9,1
65,93,Female,6,21,1,2,Premium,Quarterly,428,29,0
65,21661,Female,47,25,3,16,Premium,Monthly,989,25,0
65,21731,Male,44,12,6,11,Standard,Monthly,368,21,0

In [30]:
dff.head()

,CustomerID,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
Age,,,,,,,,,,,
22,1,Female,25,14,4,27,Basic,Monthly,598,9,1
41,2,Female,28,28,7,13,Standard,Monthly,584,20,0
47,3,Male,27,10,2,29,Premium,Annual,757,21,0
35,4,Male,9,12,5,17,Premium,Quarterly,232,18,0
53,5,Female,58,24,9,2,Standard,Annual,533,18,0

In [ ]:
df2= df['Age']
print(df2)
print(df2.mean())
print(df2.var())
print(df2.sum())
print(df2.product())
print(df2.isnull().sum())
print(df2.value_counts)
print(df.value_counts('Gender'))
print(df.value_counts('Subscription Type'))
print(df.value_counts('Contract Length'))

0        22
1        41
2        47
3        35
4        53
         ..
64369    45
64370    37
64371    25
64372    50
64373    52
Name: Age, Length: 64374, dtype: int64
41.97098207350794
193.9031549642445
2701840
0
0
<bound method IndexOpsMixin.value_counts of 0        22
1        41
2        47
3        35
4        53
         ..
64369    45
64370    37
64371    25
64372    50
64373    52
Name: Age, Length: 64374, dtype: int64>
Gender
Female    34353
Male      30021
Name: count, dtype: int64
Subscription Type
Standard    21502
Basic       21451
Premium     21421
Name: count, dtype: int64
Contract Length
Monthly      22130
Annual       21410
Quarterly    20834
Name: count, dtype: int64

In [57]:
print(df.info)

<bound method DataFrame.info of        CustomerID  Age  Gender  Tenure  Usage Frequency  Support Calls  \
0               1   22  Female      25               14              4
1               2   41  Female      28               28              7
2               3   47    Male      27               10              2
3               4   35    Male       9               12              5
4               5   53  Female      58               24              9
...           ...  ...     ...     ...              ...            ...
64369       64370   45  Female      33               12              6
64370       64371   37    Male       6                1              5
64371       64372   25    Male      39               14              8
64372       64373   50  Female      18               19              7
64373       64374   52  Female      45               15              9

       Payment Delay Subscription Type Contract Length  Total Spend  \
0                 27             Basic         Monthly          598
1                 13          Standard         Monthly          584
2                 29           Premium          Annual          757
3                 17           Premium       Quarterly          232
4                  2          Standard          Annual          533
...              ...               ...             ...          ...
64369             21             Basic       Quarterly          947
64370             22          Standard          Annual          923
64371             30           Premium         Monthly          327
64372             22          Standard         Monthly          540
64373             25          Standard         Monthly          696

       Last Interaction  Churn
0                     9      1
1                    20      0
2                    21      0
3                    18      0
4                    18      0
...                 ...    ...
64369                14      1
64370                 9      1
64371                20      1
64372                13      1
64373                22      1

[64374 rows x 12 columns]>

In [ ]:
df.describe()
##This gives you statistical summary information.

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000,64374.000000
mean,32187.500000,41.970982,31.994827,15.080234,5.400690,17.133952,541.023379,15.498850,0.473685
std,18583.317451,13.924911,17.098234,8.816470,3.114005,8.852211,260.874809,8.638436,0.499311
min,1.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,16094.250000,30.000000,18.000000,7.000000,3.000000,10.000000,313.000000,8.000000,0.000000
50%,32187.500000,42.000000,33.000000,15.000000,6.000000,19.000000,534.000000,15.000000,0.000000
75%,48280.750000,54.000000,47.000000,23.000000,8.000000,25.000000,768.000000,23.000000,1.000000
max,64374.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [ ]:
df3= df['Age']

df3.count
#Number of non-missing values.

<bound method Series.count of 0        22
1        41
2        47
3        35
4        53
         ..
64369    45
64370    37
64371    25
64372    50
64373    52
Name: Age, Length: 64374, dtype: int64>

In [75]:
df4= df['Tenure']

print(df4.mean())
print(df4.std())
print(df4.var())
print(df4.min())
print(df4.max())
print(df4.describe())
print(df4.size)
print(df4.shape)

##below Returns the column labels.

print(df.columns)
## we can also convert it into list of columns 
list_of_columns= list(df.columns)
print(list_of_columns)

31.994827104110357
17.098234043436296
292.3496074041239
1
60
count    64374.000000
mean        31.994827
std         17.098234
min          1.000000
25%         18.000000
50%         33.000000
75%         47.000000
max         60.000000
Name: Tenure, dtype: float64
64374
(64374,)
Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='object')
['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend', 'Last Interaction', 'Churn']

In [77]:
##df.types will give you the data type of each columns
df.dtypes

CustomerID            int64
Age                   int64
Gender               object
Tenure                int64
Usage Frequency       int64
Support Calls         int64
Payment Delay         int64
Subscription Type    object
Contract Length      object
Total Spend           int64
Last Interaction      int64
Churn                 int64
dtype: object

In [ ]:


df.isnull().sum()

## this is going to give the sum of missing values in the data

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64